### ISSUE TITLE
consul checks for openstack

### ISSUE THREAD

**Issue by fnpanic** [syseleven/rebootmgr#15]
Hi,

first of all great project. I cannot find the checks for openstack which are shown on slide 10 of the presentation anywhere. 

https://speakerdeck.com/stefreak/how-we-operate-an-openstack-public-cloud?slide=10

This would make the rebootmgr really useful.

Hope you can point me to the right place.

Best
Thomas

**Comment by stefreak** [comment]
These checks are not part of rebootmgr, because you could use it for any other software as well.

In the reference guide we explain how to add custom checks: https://github.com/syseleven/rebootmgr/blob/master/docs/reference.md#consul-service-monitoring

Because every cloud is different in terms of requirements and used software, I would recommend writing checks for the most important components like Galera, Storage, Network, ... in a way that they fail when the stateful clusters cannot loose a member (e.g. in galera if 3/3 masters are working, one galera node can be down with the cluster still being available).

**Comment by fnpanic** [comment]
Hi,

Thanks for the quick reply! Are there any plans to share the consul checks for Openstack and infrastructure services which would greatly benefit the entry community and would for sure drive the adoption of Rebootmgr?

If not do you know any open sourced checks which we could use with consul because the services are used by many users?

Thanks and cheers!

**Comment by stefreak** [comment]
Hi @fnpanic 

You can use any shell scripts that are available for other monitoring systems, e.g. Nagios etc.

Most of our scripts are currently very specific for our setup and it is not easy to make them useful for the general public.
